"use client";

import Image from "next/image";
import Head from "next/head";
import axios from "axios";
import { useRouter } from "next/navigation";
import Navbar from "./components/navbar";

export default function Home() {
  const router = useRouter();

  const handleSignout = async () => {
    try {
      const res = await axios.post("/api/logout");
      if (res.status === 200) {
        router.push("/");
      }
    } catch (error) {
      console.error("Logout failed", error);
    }
  };

  const handleNewSession = async () => {
    try {
      router.push("/newSession");
    } catch (error) {
      console.error("Couldn't Access Page", error);
    }
  };

  return (
    <>
      <Head>
        <title>SmartStudy | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      {/* HERO SECTION */}
      <section
        className={`w-full h-screen bg-cover bg-center bg-no-repeat flex items-center justify-center`}
        style={{ backgroundImage: `url('/background.png')` }}
      >
        <div className="text-white text-center max-w-xl px-4">
          <h1 className="text-5xl font-bold mb-6">Welcome to SmartStudy</h1>
          <p className="text-xl mb-8">A smart way to manage your study sessions</p>
          <div className="flex justify-center gap-4 flex-wrap">
            <button
              onClick={handleNewSession}
              className="font-bold px-6 py-3 bg-brand text-white rounded hover:bg-accent transition"
            >
              Create New Study Session
            </button>
            <button
              onClick={handleSignout}
              className="font-bold px-6 py-3 bg-black text-white rounded hover:bg-accent transition"
            >
              Existing Study Sessions
            </button>
          </div>
        </div>
      </section>

      {/* MAIN CONTENT */}
      <main className="px-8 sm:px-20 py-20 flex flex-col items-center gap-12 bg-white">
        <h2 className="text-3xl font-semibold">Explore Your Tools</h2>
        {/* Your additional features/components go here */}
      </main>

      {/* FOOTER */}
      <footer className="flex gap-6 flex-wrap items-center justify-center py-6 bg-gray-50 text-sm text-gray-600">
        <a
          className="flex items-center gap-2 hover:underline"
          href="https://nextjs.org/learn"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image src="/file.svg" alt="File" width={16} height={16} />
          Learn
        </a>
        <a
          className="flex items-center gap-2 hover:underline"
          href="https://vercel.com/templates?framework=next.js"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image src="/window.svg" alt="Window" width={16} height={16} />
          Examples
        </a>
        <a
          className="flex items-center gap-2 hover:underline"
          href="https://nextjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image src="/globe.svg" alt="Globe" width={16} height={16} />
          Go to nextjs.org →
        </a>
      </footer>
    </>
  );
}
